### PR TITLE
[cairo] Update to 1.17.4. JB#57056

### PR DESCRIPTION
**Pull request by pvuorela**
1.17 is development series but the 1.16 seems to be getting a little
attention and bugfixes rarely cherry-picked. Also Fedora is using this
version currently so should be good for us too.

Doc subpackage deleted. Useless since we explicitly don't build the docs.

Changes file deleted, had some bogus dates and don't think we should
bother keeping ancient version info from another project.

@spiiroin @Tomin1

### CODE REVIEW

**Comment by Tomin1** [comment]
Hmm. I got:
```
error: Installed (but unpackaged) file(s) found:
   /usr/bin/cairo-sphinx
```
while trying to build this.

**Comment by pvuorela** [comment]
The submodule in correct sha and not having any leftover files? Builds fine for me locally and in OBS.

**Comment by Tomin1** [comment]
> The submodule in correct sha and not having any leftover files? Builds fine for me locally and in OBS.

You are right. I thought I had done git submodule update and clean up any previous stuff but apparently not. Now it built fine. Well, that's good then.

**Review by Tomin1 — APPROVED** [review]
LGTM

**Pull request merged**
